/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class AccountWriterServiceModelBuilder {
    //the instance to build
    private AccountWriterServiceModel accountWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public AccountWriterServiceModelBuilder() {
        accountWriterServiceModel = new AccountWriterServiceModel();
    }

    public AccountWriterServiceModelBuilder idGender(int idGender) {
        accountWriterServiceModel.setIdGender(idGender);
        return this;
    }

    public AccountWriterServiceModelBuilder firstName(String firstName) {
        accountWriterServiceModel.setFirstName(firstName);
        return this;
    }

    public AccountWriterServiceModelBuilder name(String name) {
        accountWriterServiceModel.setName(name);
        return this;
    }

    public AccountWriterServiceModelBuilder email(String email) {
        accountWriterServiceModel.setEmail(email);
        return this;
    }

    public AccountWriterServiceModelBuilder phone(String phone) {
        accountWriterServiceModel.setPhone(phone);
        return this;
    }

    public AccountWriterServiceModelBuilder birthday(Date birthday) {
        accountWriterServiceModel.setBirthday(birthday);
        return this;
    }

    public AccountWriterServiceModelBuilder address1(String address1) {
        accountWriterServiceModel.setAddress1(address1);
        return this;
    }

    public AccountWriterServiceModelBuilder city(String city) {
        accountWriterServiceModel.setCity(city);
        return this;
    }

    public AccountWriterServiceModelBuilder postalCode(String postalCode) {
        accountWriterServiceModel.setPostalCode(postalCode);
        return this;
    }

    public AccountWriterServiceModelBuilder countryCode(String countryCode) {
        accountWriterServiceModel.setCountryCode(countryCode);
        return this;
    }

    public AccountWriterServiceModelBuilder nationality(String nationality) {
        accountWriterServiceModel.setNationality(nationality);
        return this;
    }

    public AccountWriterServiceModelBuilder optin(boolean optin) {
        accountWriterServiceModel.setOptin(optin);
        return this;
    }

    public AccountWriterServiceModelBuilder company(String company) {
        accountWriterServiceModel.setCompany(company);
        return this;
    }

    public AccountWriterServiceModelBuilder address2(String address2) {
        accountWriterServiceModel.setAddress2(address2);
        return this;
    }

    public AccountWriterServiceModelBuilder billAddress1(String billAddress1) {
        accountWriterServiceModel.setBillAddress1(billAddress1);
        return this;
    }

    public AccountWriterServiceModelBuilder billAddress2(String billAddress2) {
        accountWriterServiceModel.setBillAddress2(billAddress2);
        return this;
    }

    public AccountWriterServiceModelBuilder billCity(String billCity) {
        accountWriterServiceModel.setBillCity(billCity);
        return this;
    }

    public AccountWriterServiceModelBuilder billPostalCode(String billPostalCode) {
        accountWriterServiceModel.setBillPostalCode(billPostalCode);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public AccountWriterServiceModel build() {
        return accountWriterServiceModel;
    }
}