/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class CsvFileWriterServiceModelBuilder {
    //the instance to build
    private CsvFileWriterServiceModel csvFileWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public CsvFileWriterServiceModelBuilder() {
        csvFileWriterServiceModel = new CsvFileWriterServiceModel();
    }

    public CsvFileWriterServiceModelBuilder idProject(int idProject) {
        csvFileWriterServiceModel.setIdProject(idProject);
        return this;
    }

    public CsvFileWriterServiceModelBuilder file(String file) {
        csvFileWriterServiceModel.setFile(file);
        return this;
    }

    public CsvFileWriterServiceModelBuilder header(boolean header) {
        csvFileWriterServiceModel.setHeader(header);
        return this;
    }

    public CsvFileWriterServiceModelBuilder separator(String separator) {
        csvFileWriterServiceModel.setSeparator(separator);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public CsvFileWriterServiceModel build() {
        return csvFileWriterServiceModel;
    }
}