/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class PayinServiceModelBuilder {
    //the instance to build
    private PayinServiceModel payinServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public PayinServiceModelBuilder() {
        payinServiceModel = new PayinServiceModel();
    }

    public PayinServiceModelBuilder amount(int amount) {
        payinServiceModel.setAmount(amount);
        return this;
    }

    public PayinServiceModelBuilder returnUrl(String returnUrl) {
        payinServiceModel.setReturnUrl(returnUrl);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public PayinServiceModel build() {
        return payinServiceModel;
    }
}