/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class ProjectWriterServiceModelBuilder {
    //the instance to build
    private ProjectWriterServiceModel projectWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public ProjectWriterServiceModelBuilder() {
        projectWriterServiceModel = new ProjectWriterServiceModel();
    }

    public ProjectWriterServiceModelBuilder idTemplate(int idTemplate) {
        projectWriterServiceModel.setIdTemplate(idTemplate);
        return this;
    }

    public ProjectWriterServiceModelBuilder title(String title) {
        projectWriterServiceModel.setTitle(title);
        return this;
    }

    public ProjectWriterServiceModelBuilder estimatedTimePerTask(String estimatedTimePerTask) {
        projectWriterServiceModel.setEstimatedTimePerTask(estimatedTimePerTask);
        return this;
    }

    public ProjectWriterServiceModelBuilder nbSupplierPerTask(int nbSupplierPerTask) {
        projectWriterServiceModel.setNbSupplierPerTask(nbSupplierPerTask);
        return this;
    }

    public ProjectWriterServiceModelBuilder amountWithoutTaxPerTask(int amountWithoutTaxPerTask) {
        projectWriterServiceModel.setAmountWithoutTaxPerTask(amountWithoutTaxPerTask);
        return this;
    }

    public ProjectWriterServiceModelBuilder automaticValidation(boolean automaticValidation) {
        projectWriterServiceModel.setAutomaticValidation(automaticValidation);
        return this;
    }

    public ProjectWriterServiceModelBuilder maxEndDate(Date maxEndDate) {
        projectWriterServiceModel.setMaxEndDate(maxEndDate);
        return this;
    }

    public ProjectWriterServiceModelBuilder idCertification(Integer idCertification) {
        projectWriterServiceModel.setIdCertification(idCertification);
        return this;
    }

    public ProjectWriterServiceModelBuilder urlNotification(String urlNotification) {
        projectWriterServiceModel.setUrlNotification(urlNotification);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ProjectWriterServiceModel build() {
        return projectWriterServiceModel;
    }
}