/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class TaskValidationWriterServiceModelBuilder {
    //the instance to build
    private TaskValidationWriterServiceModel taskValidationWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public TaskValidationWriterServiceModelBuilder() {
        taskValidationWriterServiceModel = new TaskValidationWriterServiceModel();
    }

    public TaskValidationWriterServiceModelBuilder idTask(Integer idTask) {
        taskValidationWriterServiceModel.setIdTask(idTask);
        return this;
    }

    public TaskValidationWriterServiceModelBuilder state(String state) {
        taskValidationWriterServiceModel.setState(state);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskValidationWriterServiceModel build() {
        return taskValidationWriterServiceModel;
    }
}