/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class TaskLinesWriterServiceModelBuilder {
    //the instance to build
    private TaskLinesWriterServiceModel taskLinesWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public TaskLinesWriterServiceModelBuilder() {
        taskLinesWriterServiceModel = new TaskLinesWriterServiceModel();
    }

    public TaskLinesWriterServiceModelBuilder idProject(int idProject) {
        taskLinesWriterServiceModel.setIdProject(idProject);
        return this;
    }

    public TaskLinesWriterServiceModelBuilder taskColumns(List<String> taskColumns) {
        taskLinesWriterServiceModel.setTaskColumns(taskColumns);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TaskLinesWriterServiceModel build() {
        return taskLinesWriterServiceModel;
    }
}