/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class TemplateInstructionWriterServiceModelBuilder {
    //the instance to build
    private TemplateInstructionWriterServiceModel templateInstructionWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public TemplateInstructionWriterServiceModelBuilder() {
        templateInstructionWriterServiceModel = new TemplateInstructionWriterServiceModel();
    }

    public TemplateInstructionWriterServiceModelBuilder instruction(String instruction) {
        templateInstructionWriterServiceModel.setInstruction(instruction);
        return this;
    }

    public TemplateInstructionWriterServiceModelBuilder order(int order) {
        templateInstructionWriterServiceModel.setOrder(order);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TemplateInstructionWriterServiceModel build() {
        return templateInstructionWriterServiceModel;
    }
}