/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class TemplateNewWriterServiceModelBuilder {
    //the instance to build
    private TemplateNewWriterServiceModel templateNewWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public TemplateNewWriterServiceModelBuilder() {
        templateNewWriterServiceModel = new TemplateNewWriterServiceModel();
    }

    public TemplateNewWriterServiceModelBuilder idProjectType(int idProjectType) {
        templateNewWriterServiceModel.setIdProjectType(idProjectType);
        return this;
    }

    public TemplateNewWriterServiceModelBuilder title(String title) {
        templateNewWriterServiceModel.setTitle(title);
        return this;
    }

    public TemplateNewWriterServiceModelBuilder description(String description) {
        templateNewWriterServiceModel.setDescription(description);
        return this;
    }

    public TemplateNewWriterServiceModelBuilder instructions(List<TemplateInstructionWriterServiceModel> instructions) {
        templateNewWriterServiceModel.setInstructions(instructions);
        return this;
    }

    public TemplateNewWriterServiceModelBuilder columns(List<TemplateColumnWriterServiceModel> columns) {
        templateNewWriterServiceModel.setColumns(columns);
        return this;
    }

    public TemplateNewWriterServiceModelBuilder questions(List<TemplateQuestionWriterServiceModel> questions) {
        templateNewWriterServiceModel.setQuestions(questions);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TemplateNewWriterServiceModel build() {
        return templateNewWriterServiceModel;
    }
}