/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class TemplateQuestionWriterServiceModelBuilder {
    //the instance to build
    private TemplateQuestionWriterServiceModel templateQuestionWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public TemplateQuestionWriterServiceModelBuilder() {
        templateQuestionWriterServiceModel = new TemplateQuestionWriterServiceModel();
    }

    public TemplateQuestionWriterServiceModelBuilder title(String title) {
        templateQuestionWriterServiceModel.setTitle(title);
        return this;
    }

    public TemplateQuestionWriterServiceModelBuilder require(boolean require) {
        templateQuestionWriterServiceModel.setRequire(require);
        return this;
    }

    public TemplateQuestionWriterServiceModelBuilder idTemplateObjectQuestionType(int idTemplateObjectQuestionType) {
        templateQuestionWriterServiceModel.setIdTemplateObjectQuestionType(idTemplateObjectQuestionType);
        return this;
    }

    public TemplateQuestionWriterServiceModelBuilder order(int order) {
        templateQuestionWriterServiceModel.setOrder(order);
        return this;
    }

    public TemplateQuestionWriterServiceModelBuilder option(String option) {
        templateQuestionWriterServiceModel.setOption(option);
        return this;
    }

    public TemplateQuestionWriterServiceModelBuilder choices(List<String> choices) {
        templateQuestionWriterServiceModel.setChoices(choices);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TemplateQuestionWriterServiceModel build() {
        return templateQuestionWriterServiceModel;
    }
}