/*
 * FouleFactoryApiLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 09/14/2016
 */
package com.foulefactory.api.models;

import java.util.*;

public class TemplateColumnWriterServiceModelBuilder {
    //the instance to build
    private TemplateColumnWriterServiceModel templateColumnWriterServiceModel;

    /**
     * Default constructor to initialize the instance
     */
    public TemplateColumnWriterServiceModelBuilder() {
        templateColumnWriterServiceModel = new TemplateColumnWriterServiceModel();
    }

    public TemplateColumnWriterServiceModelBuilder idTemplateColumnType(int idTemplateColumnType) {
        templateColumnWriterServiceModel.setIdTemplateColumnType(idTemplateColumnType);
        return this;
    }

    public TemplateColumnWriterServiceModelBuilder column(int column) {
        templateColumnWriterServiceModel.setColumn(column);
        return this;
    }

    public TemplateColumnWriterServiceModelBuilder order(int order) {
        templateColumnWriterServiceModel.setOrder(order);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public TemplateColumnWriterServiceModel build() {
        return templateColumnWriterServiceModel;
    }
}